<a href="https://colab.research.google.com/github/Anilpattiwar/Letsupgrade--Data-Science-/blob/main/Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1
import numpy as np 
print(np.arange(2, 50, 3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:

#Q2
import numpy as np
lst1 = [] 
lst2=[]  
n = 5
for i in range(0, n): 
    ele = int(input()) 
    lst1.append(ele) 
print("List1 : ",lst1)

for j in range(0, n): 
    ele2 = int(input())   
    lst2.append(ele2) 
print("List2 : ",lst2)


import numpy 

arr = numpy.array(lst1)

print ("List1: ", lst1)

print ("Array: ", arr)

Array = numpy.array(lst2)

print ("List1: ", lst2)

print ("Array: ", Array)
arr=np.array(lst1)
Array=np.array(lst2)
print("Concatenated array")
print(np.concatenate((arr, Array), axis=None))

print("Sorted array of lst1")
lst1.sort()
print(lst1)
print("Sorted array of lst2")
lst2.sort()
print(lst2)

45
32
6
22
89
List1 :  [45, 32, 6, 22, 89]
70
55
894
4
48
List2 :  [70, 55, 894, 4, 48]
List1:  [45, 32, 6, 22, 89]
Array:  [45 32  6 22 89]
List1:  [70, 55, 894, 4, 48]
Array:  [ 70  55 894   4  48]
Concatenated array
[ 45  32   6  22  89  70  55 894   4  48]
Sorted array of lst1
[6, 22, 32, 45, 89]
Sorted array of lst2
[4, 48, 55, 70, 894]


In [ ]:
#Q3
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


In [ ]:
#Q4
>>> a = np.array([1, 2, 3, 4, 5, 6])
>>> a.shape
(6,)
>>> a2 = a[np.newaxis, :]
>>> a2.shape
(1, 6)
print(a)
>>> a = np.array([1, 2, 3, 4, 5, 6])
>>> a.shape
(6,)
>>> b = np.expand_dims(a, axis=1)
>>> b.shape
(6, 1)
print(b)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
#Q5
import numpy as np 
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#Q6
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
l1 = []  
count = 0 
for item in input_list: 
    if item not in l1: 
        count += 1
        l1.append(item)
print("No of unique items are:", count)

def unique(input_list): 
    list_set = set(input_list) 
    unique_list = list(list_set) 
    for x in unique_list: 
        print (x)
print("Unique items are:")
unique(input_list)

No of unique items are: 5
Unique items are:
1
2
4
5
8
